version: '3.8'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: wordlydb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wordlydb

  app:
    image: 'wordle:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - '8080:8080'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_url_shortener
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin12345678