spring:
  datasource:
    url: jdbc:h2:file:~/wordlydb
    username:
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2

config:
  jwt:
    secret-key: 6B5970337336763979244226452948404D635166546A576D5A7134743777217A